### ISSUE TITLE
TMP Stopped Working On Waterfox G6.6.0 Beta

### ISSUE THREAD

**Issue by thunderstone135** [onemen/TabMixPlus#460]
Hi, I just want to let you know that TMP (any version) stopped working on G6.6.0 Beta.
I reported a similar [issue](https://github.com/onemen/TabMixPlus/issues/150) before, but I doubt it's the same. I also raised a new ticket [here](https://github.com/BrowserWorks/waterfox/issues/3780).

Anyway, here's the error I receive in the console when I try to reinstall TMP:

```
1752261341215	addons.xpi	WARN	Invalid XPI: TypeError: ChromeUtils.defineModuleGetter is not a function(resource:///modules/RDFDataSource.sys.mjs:154:13) JS Stack trace: @RDFDataSource.sys.mjs:154:13
loadFromString@RDFManifestConverter.sys.mjs:31:25
loadManifest@BootstrapLoader.sys.mjs:223:38 
```

With that said, I also tried the fix posted [here](https://github.com/onemen/TabMixPlus/issues/396). No dice.

**Comment by onemen** [comment]
this issue is from Waterfox code

`ChromeUtils.defineModuleGetter is not a function(resource:///modules/RDFDataSource.sys.mjs:154:13)`

https://github.com/BrowserWorks/waterfox/blob/b0bfe88400e57478dbd5f810fda0257eef340314/waterfox/browser/extensions/common/RDFDataSource.sys.mjs#L154

**Comment by Tampa** [comment]
Still a small issue with multi-row tabs. Selecting the address bar and typing in it makes it jump to the top of the tab rows.

Tried dev build, clearing startup cache and resetting the theme.

**Comment by onemen** [comment]
@Tampa 

Do you mean it scroll to the first row as you type in the address, ir when you click enter to open new tab?

Attach a file with your Tab mix plus prefeeences

**Comment by Tampa** [comment]
[TMPpref.txt](https://github.com/user-attachments/files/22000240/TMPpref.txt)

<img width="1515" height="281" alt="Image" src="https://github.com/user-attachments/assets/88d8906c-7264-4524-a6d4-4e7b2a26a27f" />

**Comment by onemen** [comment]
@Tampa 

Tab Mix Plus does not move the address bar, check if it is don't by other extensions or scripts

**Comment by Tampa** [comment]
I'm guessing this is an issue with Waterfox specifically. The last release made changes to the address bar as well, which caused shifting to the right and it's now changed again. @MrAlex94 might be applying absolute positioning to it so it shifts where it would be with just single row.
